#!/usr/bin/env python3
# Copyright (C) 2016 Fernando Matsumoto

import sys

def printFloor(puzzleInput):
    up = puzzleInput.count('(')
    down = puzzleInput.count(')')
    print("Up: {0}    Down: {1}    Total: {2}".format(up, down, up-down))

def charPositionOnFloor(puzzleInput, n):
    if n == 0:
        return 0

    position = 0
    floor = 0
    for char in puzzleInput:
        position += 1
        floor += {'(': 1, ')': -1}[char]
        if floor == n:
            return position

    return -1

if __name__ == '__main__':
    printFloor(sys.argv[1])
    print('Char position at floor -1: ', charPositionOnFloor(sys.argv[1], -1))
