#!/usr/bin/env python3
# Copyright (C) 2016 Fernando Matsumoto

import re
import sys

def parseSue(s):
    name = s.split(':')[0]
    compounds = { comp: int(amount) for comp, amount in re.findall('(\w+): (\d+)', s) }
    return name, compounds

def isMatch(sue, readings):
    for comp, amount in sue[1].items():
        if amount != readings[comp]:
            return False
    return True

def isMatch2(sue, readings):
    for comp, amount in sue[1].items():
        if comp in ['cats', 'trees']:
            if amount <= readings[comp]:
                return False
        elif comp in ['pomeranians', 'goldfish']:
            if amount >= readings[comp]:
                return False
        else:
            if amount != readings[comp]:
                return False
    return True

def firstMatch(sues, readings, matchFunc):
    for sue in sues:
        if matchFunc(sue, readings):
            return sue
    return None

if __name__ == '__main__':
    sues = list(map(parseSue, sys.argv[1:]))
    readings = {
            'children': 3,
            'cats': 7,
            'samoyeds': 2,
            'pomeranians': 3,
            'akitas': 0,
            'vizslas': 0,
            'goldfish': 5,
            'trees': 3,
            'cars': 2,
            'perfumes': 1
            }

    print('Initial match: ' + firstMatch(sues, readings, isMatch)[0])
    print('Actual match: ' + firstMatch(sues, readings, isMatch2)[0])
