#!/usr/bin/env python3
# Copyright (C) 2015 Fernando Matsumoto

import sys

def parseInput(measuresInput):
    measures = measuresInput.split('x')
    if len(measures) != 3:
        raise ValueError('A box should have 3 measures (length, width, height): "', measuresInput, '"')
    return list(map(int, measures))

def getPaperArea(measures):
    l, w, h = measures
    sides = [l*w, l*h, w*h]
    totalArea = 2*sum(sides) + min(sides)
    return totalArea

def getRibbonLength(measures):
    l, w, h = measures
    measures = sorted(measures)
    wrap = 2 * (measures[0] + measures[1])
    bow = l * w * h
    return wrap + bow


if __name__ == '__main__':
    inputs = list(map(parseInput, sys.argv[1:]))
    
    print('Paper area: ', sum(map(getPaperArea, inputs)))
    print('Ribbon length: ', sum(map(getRibbonLength, inputs)))
