#!/usr/bin/env python3
# Copyright (C) 2016 Fernando Matsumoto

"""
Advent of Code - 2015
Day 2: I Was Told There Would Be No Math

Part One: given the sides of each box, find the total
          amount of paper required to wrap all boxes.
          Each box requires its surface area plus the
          area of its smallest side of wrapping paper.

Part Two: find the total amount of ribbon required to
          wrap all boxes. Each box requires the smallest
          perimeter of any one face plus the product of
          its side lengths of ribbon.

Formula for surface area of L*W*H box: 2LW + 2WH + 2HL.

Instruction format: each line will contain the side lengths
                    of a box separated by the character 'x'.
                    E.g. '6x10x13'.
"""

import sys

def parseInput(line):
    measures = line.split('x')
    return tuple(int(x) for x in measures)

def getPaperArea(measures):
    l, w, h = measures
    sides = [l*w, l*h, w*h]
    totalArea = 2*sum(sides) + min(sides)
    return totalArea

def getRibbonLength(measures):
    l, w, h = measures
    measures = sorted(measures)
    wrap = 2 * (measures[0] + measures[1])
    bow = l * w * h
    return wrap + bow

def run():
    inputs = [parseInput(line) for line in sys.argv[1:]]
    print('Paper area: ', sum(getPaperArea(x) for x in inputs))
    print('Ribbon length: ', sum(getRibbonLength(x) for x in inputs))

if __name__ == '__main__':
    run()
