#!/usr/bin/env python3
# Copyright (C) 2016 Fernando Matsumoto

import sys

def move(point, direction):
    x1, y1 = point
    x2, y2 = {'^': (0, 1), 'v': (0, -1), '>': (1, 0), '<': (-1, 0)}[direction]
    return (x1 + x2, y1 + y2)

def getPointsPassed(path):
    points = set()
    p = (0, 0)
    points.add(p)
    for direction in path:
        p = move(p, direction)
        points.add(p)
    return points

def getHousesPassed(fullPath, santas=1):
    paths = list(map(lambda _: [], range(santas)))
    for i, direction in enumerate(fullPath):
        paths[i % santas].append(direction)

    houses = set()
    for path in paths:
        houses |= getPointsPassed(path)
    return houses

if __name__ == '__main__':
    path = sys.argv[1]
    print('Santa has passed through', len(getHousesPassed(path)), 'houses')
    print('Santa and Robo-Santa have passed through', len(getHousesPassed(path, 2)), 'houses')
